#!/usr/bin/env python3
"""Lists all databases in MongoDB."""

from pymongo import MongoClient


if __name__ == "__main__":
	client = MongoClient("mongodb://127.0.0.1:27017")
	for db_name in client.list_database_names():
		print(db_name)
